### ISSUE TITLE
Prototype + signature fails with 5.21.8

### ISSUE THREAD

**Issue by eserte** [alexbyk/perl-evo#1]
See http://www.cpantesters.org/cpan/report/29c6944e-b12c-11e4-bbfb-958e8971dd2f for a sampe fail report and http://matrix.cpantesters.org/?dist=Evo%200.009-TRIAL for a fail/pass overview.

Maybe prototype and signature should be swapped?

**Comment by alexbyk** [comment]
thanx a lot. Looks like perl 5.21.8 have broken changes. I've fixed it https://github.com/alexbyk/perl-evo/commit/683d0d50cc7ec548c11700ab5938f5517ca8a62a

**Comment by eserte** [comment]
Do you think this should be reported to perl5-porters?

**Comment by alexbyk** [comment]
I think this was made knowingly http://perl5.git.perl.org/perl.git/commit/71917f62ec6a27775a4203ed323eb090855a4ecf

**Comment by alexbyk** [comment]
I didn't get it previously  because I didn't know what is perl5-porters. Now I got it. Yes, I think it would be nice to report this changes to perl5-porters.

**Comment by alexbyk** [comment]
mmm. We're talking about reporting "broken signatures + prototypes..." - right?

**Comment by eserte** [comment]
If I read the commit correctly, then the change was intentional, and we don't have to report anything.

And I found this paragraph in perl5.21.8's perldelta:
```
Incompatible Changes
  sub signatures moved before attributes
    The experimental sub signatures feature, as introduced in 5.20, parsed
    signatures after attributes. In this release, the positioning has been
    moved such that signatures occur in exactly the same positioning a
    prototype would be found.
```

**Comment by alexbyk** [comment]
Yes, ur right) I've read that already too)
