### ISSUE TITLE
getsockopt on non-linux systems

### ISSUE THREAD

**Issue by eserte** [alexbyk/perl-evo#2]
I observe on FreeBSD that `t/evo/net/socket.func.t` and `t/evo/net/srv/role.t` fail for the latest Evo versions (0.018x or so). It seems that you assume that the same value set with `setsockopt` is returned by `getsockopt`, but this does not seem to be the case on all systems. For example the following script

```
use strict;
use 5.010;
use IO::Socket;

my $sock = IO::Socket::INET->new(Listen => 1, LocalPort => 1234)
    or die $!;
$sock->setsockopt(SOL_SOCKET, SO_REUSEPORT, 1);
say $sock->getsockopt(SOL_SOCKET, SO_REUSEPORT);
```

run on FreeBSD would not say "1" but "512" (which is also the value of the `SO_REUSEPORT` define).

Maybe instead of using `is()` in the tests you should just check for true/false, i.e. by using `ok()`.

**Comment by alexbyk** [comment]
@eserte Thank's for the info. I've already seen this report from cpantesters and 've already fixed this by https://github.com/alexbyk/perl-evo/commit/d8f15511355ff96eeb14f3c4a0559a41f34a7c83 . If I miss something, I'll fix it when I'll read the next cpantester report.
